// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cenqkmatqpvifgbptyyw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlbnFrbWF0cXB2aWZnYnB0eXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0NzM5ODIsImV4cCI6MjA1NTA0OTk4Mn0.HDM18ZQzjIePEKGFdcwi-I__lwOebt60v3RHb1ePw6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);